#!/bin/sh

set -ev

# Make sure we can run git add from out of tree:
export GIT_DIR=`pwd`/.git
export GIT_INDEX_FILE=`pwd`/$GIT_INDEX_FILE

# Create a clean temp directory for running tests:
TEMPDIR=`mktemp -d -t testing-XXXXXXXXX`
git checkout-index --prefix=$TEMPDIR/ -af
cd $TEMPDIR

# Here is the bit where we check that everything compiles.  If we want
# to run a test suite, we should do that here.
which gb || (echo You need to install gb to build entomonitor && exit 1)

gb

# Now let's gofmt everything...

GIT_WORK_TREE=$TEMPDIR
# First we format everything and add all our changes to the repository!
find . -name '*.go' -exec echo gofmt -w '{}' \; -exec gofmt -w '{}' \; \
    -exec git add '{}' \;

cd ..
rm -rf $TEMPDIR

echo Tests all passed!
